---

num_clients: 10 #100 total number of clients
total_clients: 10 #100 total number of clients
num_epochs: 5 #10 number of local epochs
batch_size: 5 #10
num_rounds: 10 #100
clients_per_round: 1 #10
stragglers_fraction: 0.9
learning_rate: 0.03
mu: 1.0 # it can be >= 0

client_resources:
  num_cpus: 1
  num_gpus: 0.0

server_device: cpu

dataset_config:
  iid: false
  balance: false
  power_law: true

fit_config:
  drop_client: false # with FedProx, clients shouldn't be dropped even if they are stragglers

model:
  _target_: FedFA.models.Net
  num_classes: 10

# da repo fedml Alessio
strategy:
  _target_: flwr.server.strategy.FedAvg
  fraction_fit: 0.00001
  fraction_evaluate: 0.0
  min_fit_clients: ${clients_per_round}
  min_evaluate_clients: 0
  min_available_clients: ${total_clients}