---
num_clients: 100 #100 total number of clients
total_clients: 100 #100 total number of clients
num_epochs: 10 #10 number of local epochs
batch_size: 10 #10
num_rounds: 10 #100
clients_per_round: 10 #10
stragglers_fraction: 0.9
learning_rate: 0.03
mu: 0.0 # # it should be zero always
is_local: true

client_resources:
  num_cpus: 1
  num_gpus: 0.0

server_device: cpu

dataset_config:
  dataset: "cifar10" # can be "cifar100" or "cifar10"
  alpha_dirichlet: 0.3 # can be 0.3, 0.6

fit_config:
  proximal_mu: ${mu}
  drop_client: true

# da repo fedml Alessio
strategy:
  #_target_: flwr.server.strategy.FedAvg
  _target_: flwr.server.strategy.FedAvg
  fraction_fit: 0.00001
  fraction_evaluate: 0.0
  min_fit_clients: ${clients_per_round}
  min_evaluate_clients: 0
  min_available_clients: ${total_clients}